### ISSUE TITLE
Working with Free Variations?

### ISSUE THREAD

**Issue by morganhvidt** [JDGrimes/edd-sl-free#5]
I've been trying to allow auto updates at all times, regardless of the license status. I'm using free price variations. I'm lost haha. Much appreciated if you can point me in the right direction 😄

**Comment by JDGrimes** [comment]
I haven't worked with free variations, but I think it would be possible to achieve what you want by modifying the code of this plugin. I guess you would need to have it check which variation the user purchased, rather than just the extension price, when determining whether a download is free. Since I haven't worked with variations before, I don't know off of the top of my head how to do that, though.
